### ISSUE TITLE
getLoader is not a function

### ISSUE THREAD

**Issue by roryclaasen** [aze3ma/react-app-rewire-scss#12]
Using the latest version of react app rewired, I am unable to use the package.
`getLoader` is no longer available.

```shell
> react-app-rewired start

getLoader is not a function
npm ERR! code ELIFECYCLE
npm ERR! errno 1
```

Dependencies
```json
"react-app-rewire-scss": "^1.0.2",
"react-app-rewired": "^2.0.2"
```

**Comment by imVinayPandya** [comment]
any solutions @roryclaasen

**Comment by roryclaasen** [comment]
@imVinayPandya I downgraded `react-app-rewired` to `1.6.2` and that works.
I have just tried the latest versions of the packages and it is still broken unfortunately

**Comment by roryclaasen** [comment]
Closing this while tidying up my active issues.
I also don't use this package anymore and it looks like it hasn't been updated in a while
