### ISSUE TITLE
Vulnerabilities

### ISSUE THREAD

**Issue by nataly-chobat** [aze3ma/react-app-rewire-scss#2]
Could you please update dependencies?
`react-app-rewire-scss > node-sass > request > tunnel-agent`
`react-app-rewire-scss > node-sass > request > hawk > sntp > hoek`
`react-app-rewire-scss > node-sass > request > hawk > hoek`
`react-app-rewire-scss > node-sass > request > hawk > cryptiles > boom > hoek`
`react-app-rewire-scss > node-sass > request > hawk > boom > hoek`

The message about these vulnerabilities are really annoying every time when install new package. If it is possible from your side, please, fix it.

All info about vulnerabilities can be seen after running command `npm audit`.

Also thanks for such great package which helps to reduce a lot of time in development!

**Comment by aze3ma** [comment]
@nataly-chobat Thank you.

I think it's from node-sass side so they depends on outdated version of hoek@2.16.3 you can check [#2352] (https://github.com/sass/node-sass/issues/2352)
[#2288] (https://github.com/sass/node-sass/issues/2288)
[#2262] (https://github.com/sass/node-sass/issues/2262)
[#2252] (https://github.com/sass/node-sass/issues/2252)
[#2256] (https://github.com/sass/node-sass/issues/2256)
[#2170] (https://github.com/sass/node-sass/issues/2170)
also you're more than welcome if you want to file a PR.

**Comment by nataly-chobat** [comment]
thanks for your answer!
You absolutely right, these vulnerabilities are caused by node-sass

Another question: why do you include less loader if it is not devMode?

**Comment by aze3ma** [comment]
@nataly-chobat Sorry it was wrong one SOLVED.
