### ISSUE TITLE
react-app-rewire-scss not in Community Maintained Rewires.

### ISSUE THREAD

**Issue by ghost** [aze3ma/react-app-rewire-scss#5]
If I go here: https://github.com/timarney/react-app-rewired/tree/master/packages

I can see this: https://github.com/timarney/react-app-rewired/tree/master/packages/react-app-rewire-sass

but it says: `This package has been deprecated and moved to react-app-rewire-scss`.

But it doesn't show in **Community Maintained Rewires** in Readme. **Why**?

**It's easier to use** than facebook's solution (https://github.com/facebook/create-react-app/blob/master/packages/react-scripts/template/README.md#adding-a-css-preprocessor-sass-less-etc)?

**Comment by aze3ma** [comment]
@johnunclesam check it out it's just merged the update of README [loaders](https://github.com/timarney/react-app-rewired#loaders)
