### ISSUE TITLE
Change "than" to "then"

### ISSUE THREAD

**Issue by stephenfriedman** [aze3ma/react-app-rewire-scss#8]
Regarding line 16 in `README.md`:

The context of the grammar here seems semi-important:

As-is meaning: Rewire your app _as opposed to_ modifying config-overrides.js

Should be: Rewire your app and then modify config-overrides.js

TLDR: change "than" to "then"

**Comment by aze3ma** [comment]
@stephenfriedman  Thank you for your attention.
